### ISSUE TITLE
Add info about currently processed task into executor-docking

### ISSUE THREAD

**Issue by skodapetr** [cusbg/prankweb#147]
As of the the std output contains only output of the AutoDock Vina .. would be better to output some information so we can use the logs to figgure out which docking task is beeing executed.

**Comment by luk27official** [comment]
I have added it into my branch in this commit: https://github.com/luk27official/prankweb/commit/cc0701cb79e40eda4eb28daf07698efe7070b60c

Hopefully it's enough, I will close the issue later once it's fully merged.
