### ISSUE TITLE
prankweb problem encauntered

### ISSUE THREAD

**Issue by sanyiimagarsaa** [cusbg/prankweb#153]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
![Screenshot (203)](https://github.com/user-attachments/assets/7b08ef61-d54d-43ef-9a05-6d15b0254437)

**Comment by luk27official** [comment]
Hello, I couldn't find an AlphaFold entry of `AFQ8IIS4F1`, so this is expected behavior.

**Comment by luk27official** [comment]
Just a note - I think you might want to use this `Q8IIS4` instead.

**Comment by sanyiimagarsaa** [comment]
Thank you
