### ISSUE TITLE
Add link to file a github issue on the web

### ISSUE THREAD

**Issue by davidhoksza** [cusbg/prankweb#25]
on the main page or about pae

**Comment by skodapetr** [comment]
```kazdoapdne co se tyka toho jak reportovat issues, tak by to mohlo byt v napovede a mozna opravdu link z menu jako report issues. a tam bych ale napsal, ze preferujeme submitnuti issue na github, pripadne poslani emailu```

**Comment by skodapetr** [comment]
Add links in 33602994ab2d69ce4320ef70f23df7a7d86e9dc0.
