### ISSUE TITLE
Can't load MSA (or any file) from a file

### ISSUE THREAD

**Issue by davidhoksza** [cusbg/prankweb#26]
On Mac

**Comment by davidhoksza** [comment]
[msa.zip](https://github.com/cusbg/prankweb/files/5422393/msa.zip)

**Comment by skodapetr** [comment]
Seems like it might be connected to https://stackoverflow.com/questions/47386981/input-type-file-attribute-accept-not-working-in-safari-on-macbook , to quote 
``` Indeed it seems Safari doesn't accept files' extensions as accept attribute... ```
as I'm not aware of any standard mime types for sequences it seems like to only option is to remove ```accept``` completely from the input element.

**Comment by davidhoksza** [comment]
The file is always a text file, however, the file suffix tends to vary substantially.

**Comment by skodapetr** [comment]
MSA will be removed, #67.
