### ISSUE TITLE
Provide option to download raw P2Rank output

### ISSUE THREAD

**Issue by rdk** [cusbg/prankweb#31]
It should be possible to download complete output of P2Rank including calculated conservation scores. This is useful not only because PrankWeb doesn't present all information P2Rank can calculate but also for debugging.

Old version of PrankWeb allows it. New version only allows to download pymol visualizations.

**Comment by skodapetr** [comment]
So it is not complete output of p2rank as p2rank does not output the conservation, but output for example *params*. Anyway MSA and conservation files are now part of the download file.
