### ISSUE TITLE
Show chains after return from the results page

### ISSUE THREAD

**Issue by davidhoksza** [cusbg/prankweb#33]
When the user returns from the results page to the main page, the structure chains do not show. To make them appear, one has to reenter the PDB ID.

**Comment by skodapetr** [comment]
Well it should be possible to show all the availablae chains. If we want to show the selected chains, we probably need to add hidden form field to preserve the value. 

@davidhoksza What is the expected behaviour?

**Comment by davidhoksza** [comment]
When you return to the main page you should see it in the same state as when you left it.

**Comment by skodapetr** [comment]
The idea is to employ hidden input field to store the selected chains. While the implementation can be improved. Any misfunction or bugs should be addressed by new issues.
