### ISSUE TITLE
The downloaded results archive contains a PDB file without any ligands

### ISSUE THREAD

**Issue by davidhoksza** [cusbg/prankweb#38]
When the archive with the results is downloaded, it contains actually two PDB files, one in the root of the archive and one in the visualization/data folder. Both are named `structure`. However, the one, which is loaded with the pml script is actually a stripped version of the full PDB file and does not contain any information about any ligand. 

When I try to run the predictions with the latest P2rank everything works well.

**Comment by skodapetr** [comment]
Yes, as the version given to p2rank contains only data for selected chains, or all chains. 
So a solution is to either replace the structure file created by p2rank by the full strcuture file But I'm not sure whether that would work @rdk ?
Or move chain selection (filtering) to p2rank - @rdk?

@davidhoksza So which one should we choose?

**Comment by davidhoksza** [comment]
But first, this is a ligand and not a polypeptide chain. And second, I did not filter on chains. E.g. in 6y2f, there is actually a single polypeptide chain so in this specific case it makes even less sense not to have the ligand in the output.

So the question is, whether you could filter out only what the user explicitly selected to filter out (I mean in the form on the main page). And the ligands are never offered...

**Comment by skodapetr** [comment]
I think I see your point. It might be possible, but then some ligands are for example part of a chain. 
And from user experience I would actually expect to see the whole strcuture with predictions only on selected chains. 

But if you are sure that it make sense to just cut-out (basically as it is now) what user does not select ... then we can perform such modification.

**Comment by skodapetr** [comment]
After some internal discussion the solution should be:
 * User can select chains
 * We filter out chains that user does not select - i.e. the filter is negative
 * This filter applies only for AMINOACID, i.e. other chain types are not filtered
   using this option

**Comment by skodapetr** [comment]
It turns out that the usr provided PDB code corresponds to multiple chains including non-protein chains. So before implementing a negative filter we should try this approach first.

**Comment by skodapetr** [comment]
It seems that while the ligand is visible in the online view, it is not visible in the download. 
For example here http://skoda.projekty.ms.mff.cuni.cz/p2rank/analyze?database=v2-conservation&code=6Y2F_A
