### ISSUE TITLE
The log should not be red

### ISSUE THREAD

**Issue by davidhoksza** [cusbg/prankweb#48]
Assign different colors to the debug, info, and warning messages which appear when waiting for the results.

**Comment by skodapetr** [comment]
Suugested solutions:
* We can start by changing the color to something else ... black?
* As a next step we can use "unified messages" fot the output (in Python script and p2rank). Next we can parse the text in frontend and create HTML with colors.

**Comment by skodapetr** [comment]
The log color is now dark blue.
