### ISSUE TITLE
Submitting an empty protein

### ISSUE THREAD

**Issue by davidhoksza** [cusbg/prankweb#50]
When the user deselects all chains at the input, the computation proceeds (starts to collect MSA and so on) and even does the prediction. Instead, we should maybe disable the submit button and, in the optimal case, show a warning/error message.

**Comment by skodapetr** [comment]
Unchecking all chains leads to situation where all chains are used. The only one issue is that such prediction, without any chains given, can still be executed by directly acessing the URL.  Should we also prevent that from happening? So for example such prediction run would fail.

**Comment by skodapetr** [comment]
We decided to not support such behavior, i.e. user must choose at least one chain or use the structure as it is.
