### ISSUE TITLE
Given prediction was not found. 

### ISSUE THREAD

**Issue by miriam-13** [cusbg/prankweb#53]
Hi, I have been trying to upload my own PDB file (that is not in the https://www.rcsb.org database) and keeps saying given prediction was not found. Anyone could help me with it? I acquired the PDB formant from two different sources and neither of them works. thank you

**Comment by skodapetr** [comment]
@miriam-13 Thank you for reporting the issue, I try to do my best to resolve it in this week (before Friday).
I already know what causes the "Given prediction was not found. " message, but there might be another issue I may have to look into.

**Comment by miriam-13** [comment]
Thanks a lot!

**Comment by skodapetr** [comment]
@miriam-13 I've done some fixes, if you need the prediction ASAP you can use my develop instance at http://skoda.projekty.ms.mff.cuni.cz/p2rank/ .

The production should be fixed in1-3 days.

**Comment by miriam-13** [comment]
This helped a lot! Thank you for your help.
