### ISSUE TITLE
Ligand information required

### ISSUE THREAD

**Issue by heeqee** [cusbg/prankweb#68]
Hi, Prankweb is a great tool. But It only gives pocket information. I want to know which ligand is bound to the pocket. Could you add the feature to your website?
Thank you very much!

**Comment by skodapetr** [comment]
Hi, as of now we detect he ligand from the structure file. So to every detected binding site we have the information about the "ligand". Do you have any suggestion how should this information be presented to the user?
Perhaps as a tab on the right site? So we have _pockets_ and _predicted pockets_. Where the first one contains information about the detected binding sites + information about the ligands. And the second one is same as now.

Or was the idea to actually load (from external databases) all known ligands for given structure, and provide known binding sites based on this information?

**Comment by heeqee** [comment]
Hi,
Thank you for your reply. I can not find the ligand information in pockets section. The screenshot is here.
![Screenshot_20211211-104512](https://user-images.githubusercontent.com/94897442/145661879-6251637d-2c53-4315-b804-936d7c03a3ba.png)

**Comment by skodapetr** [comment]
I see this is section with predicted pocket sides, we do not have any information about suitable ligands available. But it may be interesting to integrate that with some ligand prediction sw. to provide user with additional information. On the other hand I would expect that this step would be, most of the time, carried out by experts using docking etc. 

The information about existing _binding sites_ is available in the sequence view. But you are right that is hard to find and even harder to see on the structure - more so on phone.
![image](https://user-images.githubusercontent.com/3341693/145669568-0354c98f-21a6-4ae5-8b67-3d3529ff2578.png)

Was your question concerned with the first point, i.e. predicting ligands, or the second point i.e. make it easier for user to see "detected" binding sites, with the extension of loading all known binding sites from some database.

**Comment by heeqee** [comment]
Hi
I'm more concerned about the ligands at the binding site. You're right. If it's possible to integrate molecular docking into prankWeb, that would be great. Thank you for your kind reply.
