### ISSUE TITLE
ELIXIR integration

### ISSUE THREAD

**Issue by rdk** [cusbg/prankweb#7]
On the welcome page and on the result page there is Elixir logo with no links or explanation. What is Elixir and what else it can do for me?

How it may look like: https://webchem.ncbr.muni.cz/Platform/ChargeCalculator

Also, P2Rank/PrankWeb is not listed among Elixir services https://www.elixir-czech.cz/services

**Comment by skodapetr** [comment]
Listing of PrankWeb can not be solved within this repository.
