### ISSUE TITLE
Enable prediction on AlphaFold DB (ADB)

### ISSUE THREAD

**Issue by davidhoksza** [cusbg/prankweb#71]
Once the AlphaFold model  (@davidjakubec) is available, the following functionality needs to be implemented:

- [x] Enable entering UniProt ID (as an alternative to PDB ID). There should be two tabs, one showing labeled "experimental structures" while the other labeled "predicted structures". Experimental structures tab will feature the current functionality while the predicted structures will enable entering UniProt ID.
- [x] Obtain information about available AF model by fetching data from https://alphafold.ebi.ac.uk/api/prediction/{uniprot_accession}
- [x] Download the model
- [x] Extract per-residue confidence scores (pLDDT) from the structure file (either mmCIF or PDB). In PDB these are stored as b-factors; in mmCIF they are made available via the *_ma_qa_metric* loop.
- [x] Use the AF model for prediction (or use an already stored predictions).
- [x] Visualize the prediction with pLLDT scores shown the same way as conservation (bars in the sequence view + the possibility to color the structure by it).
- [x] Show a warning to the user, that this is a predicted and not an experimental structure.

**Comment by rdk** [comment]
There will be now for prediction models provided via PrankWeb:
- default
- conservation_hmm
- alphafold_conservation_hmm
- alphafold

We should emphasize somewhere in the UI that the alphafold models differ in that they don't depend on the b-factor feature and that they are also more suitable for NMR and cryo-EM structures. In the feature this model suggestion/selection could be done automatically based on the input.

**Comment by skodapetr** [comment]
The implementation is not precise but any suggestions and modification requests should take in new issues. 

As of the model suggestion, at this time we probably do not have enough information how to suggest this and also the UI may not be prepared for this. Yet I would appreciate if @rdk elaborate on that idea in  new issue.
