### ISSUE TITLE
Make all PDB and AF predictions available as download.

### ISSUE THREAD

**Issue by davidhoksza** [cusbg/prankweb#72]
Let the user download all the prediction for PDB and AF. 

There should be a new Download section where the user will be have the possibility to download all the PDB or AF predictions => 2 links. In the optimal scenario, the section should feature for each archive to which date the structures were downloaded/predicted and how many structures are in each of the archives.

**Comment by skodapetr** [comment]
@davidhoksza What should be content of the archive? all the output from p2rank or only the CSV files?

**Comment by davidhoksza** [comment]
Depends on the size of the archive. I would go for everything given the size is manageable.

**Comment by rdk** [comment]
I'm guessing it will be 50-100GB or more just for PDB with visualizations. How about ftp or rsync access?

**Comment by skodapetr** [comment]
The last estimate I got is that visualizations should consume roughly 130 GB for PDB and at least twice as much for AF. The whole "directory" may be 200G for PDB and 400GB AF.

**Comment by skodapetr** [comment]
The files with only predictions are now available, yet I think we improve the access by better structuring the content or providing other interface e.g. FTP.
