### ISSUE TITLE
Pipeline for automatic download of new PDB structures. 

### ISSUE THREAD

**Issue by davidhoksza** [cusbg/prankweb#73]
A job which would periodically check for new structures in PDB, predict sites for them and made them available for download (see issue #72).

**Comment by skodapetr** [comment]
@davidhoksza Any suggestion how to get list of relevant PDB entries?

**Comment by davidhoksza** [comment]
@skodapetr What do you mean by "relevant"? Added with respect to the last time the PDB was queried?

**Comment by skodapetr** [comment]
The job is using prankweb API and expose the data using the same API.
